# Generated by Django 4.2 on 2024-03-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_portfolio_alter_student_major_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='portfolio',
        ),
    ]
